version: 0.2
phases:
  install:
    commands:
      - aws codeartifact login --tool npm --repository nextwork-devops-cicd --domain nextwork --domain-owner 300042230375 --region us-east-1
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
    - appspec.yml
    - scripts/**/*
  discard-paths: no